### ISSUE TITLE
Features Question

### ISSUE THREAD

**Issue by mkeplinger** [jforrest/Chargify-PHP-Client#1]
How does this one differ from http://github.com/lewsid/chargify_api_php???

I see that you have added all of the new API methods.  We have already integrated http://github.com/lewsid/chargify_api_php into our code.  Is yours compatible with that one?

**Comment by mkeplinger** [comment]
jforrest replied:

This one has basically the same class names, but beyond that there are several differences.
1. This one uses libcurl functions instead of exec curl, which allows for much more flexibility and debugging information.
2. It allows the option to use JSON or XML, instead of only XML.
3. The full API is implemented, instead of a small subset.
4. You can use the API with only the Chargify object classes, instead of ChargifyConnector.
5. You can export raw XML and JSON based on the property values in the Chargify objects.
6. You can use the ChargifyConnector alone, and use raw XML or raw JSON. (using the request.. and retrieve.. functions directly)
7. Error conditions raise exceptions instead of returning error strings which need to be parsed to determine type.

In general, I made many non-backward compatible changes with regards to the other API client, so I felt it would be less confusing to start a new project.

(Thanks for putting this together)

**Comment by jforrest** [comment]
Also to answer your second question, It shouldn't take much to be compatible, but I wouldn't know without knowing your codebase. Also, thanks again for the heads up on the API key, no telling how long I would have taken to notice it.
