### ISSUE TITLE
getAllCustomers ignores page numbers

### ISSUE THREAD

**Issue by abraham** [jforrest/Chargify-PHP-Client#2]
Code used:
    $customer = new ChargifyCustomer(NULL, $test);
    $customers = $customer->getAllCustomers(2);

I had to hack in `$page` being passed on through `getAllCustomers()` in `ChargifyCustomers.php` and `getAllCustomers()` in `ChargifyConnector.php`.

**Comment by abraham** [comment]
Committed to my fork: 5ce3885029bc812eb9c68f14d3052fd120e0d5d7

**Comment by jforrest** [comment]
thanks! I pushed your changes with the fix.
