### ISSUE TITLE
No way to populate ChargifyConnector object in ChargifyCustomer

### ISSUE THREAD

**Issue by brandonsavage** [jforrest/Chargify-PHP-Client#3]
The ChargifyCustomer::__construct() method creates an instance of ChargifyConnector, but does not allow for the passing of any configuration options (such as the API key and the domain). This results in certain failure when using the $customer->create() method.

Proposed solution: require that the ChargifyConnector object be injected into the constructor, or add a method that allows its introduction and throws an exception if one is not present before attempting to send data to Chargify.

**Comment by jforrest** [comment]
Are you using multiple Chargify keys/domains in the same code?

**Comment by brandonsavage** [comment]
No, we're using the same chargify key and domain for the whole codebase.
