### ISSUE TITLE
create subscription for an existing user?  Seems to only work for new users...

### ISSUE THREAD

**Issue by ghost** [jforrest/Chargify-PHP-Client#4]
I'm probably doing something wrong, but I was trying to add a subscription to an existing user.  (I need to be able to switch them at a later date).  It appears that the create subscription, when given a user object, it tries to create a user and subscription at the same time and doesn't send just a customer_id along with a "sign this existing user up" type of format.  You can see in the request it's including my existing userid (999999).  - <not really 999999>.

Anyway - I've hacked around it and created my own quick function to POST the expected format so I'm ok - but wanted to ask or inform you in case it's a bug after all.

POSTDATA

<?xml version="1.0" encoding="utf-8"?>
<subscription><credit_card_attributes><full_number>1</full_number><cvv>234</cvv><billing_address>1334 sinbad way</billing_address><billing_city>mycity</billing_city><billing_state>IL</billing_state><billing_zip>93933</billing_zip><billing_country>US</billing_country><expiration_month>12</expiration_month><expiration_year>2010</expiration_year><first_name>MYNAME</first_name><last_name>blah</last_name></credit_card_attributes><customer_attributes><email>myemail@myprovider.com</email><first_name>MYNAME</first_name><last_name>blah</last_name><organization></organization><reference>65</reference><id>999999</id><created_at>2010-07-27T18:13:11-04:00</created_at><updated_at>2010-07-27T18:49:09-04:00</updated_at><address></address><address_2></address_2><city></city><country></country><phone></phone><state></state><zip></zip></customer_attributes><product_handle>freetrial</product_handle></subscription>
END POSTDATA

RESULT

stdClass Object
(
    [response] => <?xml version="1.0" encoding="UTF-8"?>
<errors>
  <error>Customer: cannot be blank.</error>
  <error>A Customer must be specified for the subscription to be valid.</error>
</errors>

```
[code] => 422
[meta] => Array
    (
        [url] => https://company.chargify.com/subscriptions.xml
        [content_type] => application/xml; charset=utf-8
        [http_code] => 422
        [header_size] => 730
        [request_size] => 1148
        [filetime] => -1
        [ssl_verify_result] => 0
        [redirect_count] => 0
        [total_time] => 0.204355
        [namelookup_time] => 2.1E-5
        [connect_time] => 0.01465
        [pretransfer_time] => 0.077318
        [size_upload] => 0
        [size_download] => 182
        [speed_download] => 890
        [speed_upload] => 0
        [download_content_length] => 182
        [upload_content_length] => 0
        [starttransfer_time] => 0.204326
        [redirect_time] => 0
    )
```

)
END RESULT

Looks like when I have an existing user the request should look like this (using a customer_id rather than a full set of customer_attributes):

Scenario: Create a subscription using an existing customer ID
    Given I have 1 product
    And I have 1 customer
    And I have this xml subscription data
      """
        <?xml version="1.0" encoding="UTF-8"?>
        <subscription>
          <product_handle>[@product.handle]</product_handle>
          <customer_id>[@customer.id]</customer_id>
          <credit_card_attributes>
            <full_number>1</full_number>
            <expiration_month>10</expiration_month>
            <expiration_year>2020</expiration_year>
          </credit_card_attributes>
        </subscription>
      """
I put this function in ChargifySubscription and was able to use my existing customer id...

public function updateExistingCustomerSubscription($producthandle, $customer, $cc, $format = 'XML') {

```
    $subscriptionRequest =  
    '<?xml version="1.0" encoding="UTF-8"?>
    <subscription>
      <product_handle>' . $producthandle . '</product_handle>
      <customer_id>' . $customer->id . '</customer_id>
      <credit_card_attributes>
        <full_number>' . $cc->full_number . '</full_number>
        <expiration_month>' . $cc->expiration_month . '</expiration_month>
        <expiration_year>' . $cc->expiration_year . '</expiration_year>
      </credit_card_attributes>
    </subscription>';

    return $this->connector->requestCreateSubscription($subscriptionRequest, $format);
}
```

**Comment by jforrest** [comment]
Did you try setting the customer_id field on the subscription object? I think this would be the best way to accomplish what you are trying.
Basically, whatever properties on the subscription object that you set will be present in the xml. You can call the getXML() function on the subscription object to verify it matches what you need (it will match what is sent to the chargify API).

**Comment by ghost** [comment]
Hmm, your solution is so much more elegant than mine.  That's what I get for being an IT guy and not a developer.  :)  You rock.

That worked - thanks!
