### ISSUE TITLE
Updating CC Information

### ISSUE THREAD

**Issue by josephfung** [jforrest/Chargify-PHP-Client#6]
When updating the CC information using $subscription->updateCreditCard I get the following error "Customer code to modify does not exist"

Assuming the subscription information had to include the customer information prior to sending the details to Chargify, I added 

```
    $chargify_subscription = $this->getSubscriptionsByID($subscription_id);
```

To line 457 in ChargifyConnector.php to pre-load the subscription information. That eliminated the error, but didn't actually result in any updates to the subscription. Suggestions?

**Comment by jforrest** [comment]
I am very sorry, I didn't notice this issue before. Are you still having problems with this?

**Comment by josephfung** [comment]
No, I'm not experiencing the issue any more, however I can't recall what I changed to get it to work. I undid the change above, so I have to assume there was some other factor at play.
